name: EKS Multi-Tenant CI/CD

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant Name'
        required: true
      environment:
        description: 'Environment (dev, uat, prod)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 746669234841.dkr.ecr.us-east-1.amazonaws.com/testing/roger

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ github.event.inputs.tenant }}-${{ github.event.inputs.environment }}-nginx
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME:latest 746669234841.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
        docker push 746669234841.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend-config="key=terraform-state/${{ github.event.inputs.tenant }}-${{ github.event.inputs.environment }}/eks.tfstate"

    - name: Terraform Workspace
      run: |
        terraform workspace new ${{ github.event.inputs.tenant }}-${{ github.event.inputs.environment }} || terraform workspace select ${{ github.event.inputs.tenant }}-${{ github.event.inputs.environment }}

    - name: Terraform Apply
      run: terraform apply -var-file="tenant-prod.tfvars" -auto-approve
